# Generated by Django 4.1.7 on 2023-03-12 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_remove_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
